FROM alpine:3.20

RUN apk add --no-cache curl jq bash

COPY register-connectors.sh /register-connectors.sh
RUN chmod +x /register-connectors.sh

COPY connectors /connectors

ENTRYPOINT ["/register-connectors.sh"]
